# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:15.0.2


      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    working_directory: ~/repo


    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout


      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-


      - run: gradle dependencies


      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}


      # run tests!
    # - run: gradle test
  test:
    docker:
      - image: cimg/openjdk:15.0.2
    steps:
      - checkout
      - run: gradle test
deploy:
  docker:
    - image: cimg/openjdk:15.0.2
  steps:
    - checkout
    - run: echo "Deploy"


workflows:
  build-test-validate-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - validate:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - validate
